### ISSUE TITLE
[front-end] Decline request logic in doctor Inbox screen 

### ISSUE THREAD

**Issue by ZhihangZhang** [SongWithoutWords/mapp#36]

**Comment by SongWithoutWords** [comment]
This will require #42, I'll try to get that done either today or tomorrow

**Comment by ZhihangZhang** [comment]
`/requests/#Int RequestR DELETE`
Is the integer the id of the doctor's pending request?
Do I need to put anything in the request body or header?

**Comment by SongWithoutWords** [comment]
As mentioned on FB the "id" you're looking at there is of the patient.

I'll create an issue to include the id of the request so that it can be declined with DELETE /requests/ID

**Comment by SongWithoutWords** [comment]
@ZhihangZhang, I've fixed #44 and deployed a new version of the server, so you should be good to go

**Comment by ZhihangZhang** [comment]
![Imgur](https://i.imgur.com/84Cuvik.png)
Any idea why I got the internal server error? Am i missing something in the request?

**Comment by SongWithoutWords** [comment]
Hey @ZhihangZhang, that's on me and should be quick to fix.

**Comment by SongWithoutWords** [comment]
I've deployed a version with the fix - give it a minute or two and it should be good to go
