### ISSUE TITLE
Integrate Medication Allergies and Health Conditions fields into patient Sign-Up screen in frontend

### ISSUE THREAD

**Issue by amirtootooni** [SongWithoutWords/mapp#38]

**Comment by SongWithoutWords** [comment]
Hey @amirtootooni, why is this considered core functionality? I can't see it anywhere in our M1 Requirements doc, would be good to focus on stuff that we'll be evaluated on.

**Comment by SongWithoutWords** [comment]
I don't see it in our design doc either.

**Comment by SongWithoutWords** [comment]
I'm going to close this as out of scope because it doesn't relate to any of our deliverables - reopen and we can chat about it if you like, but with 9 days to go I'd like to focus on our core deliverables.
