### ISSUE TITLE
Include email and password in request header for authentication when making requests from client

### ISSUE THREAD

**Issue by SongWithoutWords** [SongWithoutWords/mapp#5]

**Comment by amirtootooni** [comment]
Need to decide on authentication method first

**Comment by SongWithoutWords** [comment]
@amirtootooni, because this method is so easy, do you think we should implement this first and improve on it later? It might then be easy enough to improve later if there was a function in the fronted for making HTTP requests to the server that handles authentication, so any future improvement could be done in one place

**Comment by amirtootooni** [comment]
Sure. I'll try and get at it tomorrow, right now priority for me is to get the app working on android, then setting up the prescription creation UI. If you need this to be done asap maybe @ZhihangZhang can help out?

**Comment by SongWithoutWords** [comment]
No rush - getting the emulator working is for sure important

**Comment by SongWithoutWords** [comment]
@amirtootooni, could you start on this today? I don't want to leave authorization too late in case it breaks things initially

**Comment by amirtootooni** [comment]
This was done by george 2 weeks ago

**Comment by SongWithoutWords** [comment]
lol

**Comment by SongWithoutWords** [comment]
@ZhihangZhang, can you confirm this is done before I deploy a version of the server with authentication/authorization?

The request (specifically the Authorization header) needs to look something like the following:

```~/D/s/c/c/notes> http -v -a user@password.com:password agis-mapp.xyz/doctors
GET /doctors HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic dXNlckBlbWFpbC5jb206cGFzc3dvcmQ=
Connection: keep-alive
Host: agis-mapp.xyz
User-Agent: HTTPie/0.9.8```

Where dXNlckBlbWFpbC5jb206cGFzc3dvcmQ= is a base64 encoding of user@email.com:password

**Comment by SongWithoutWords** [comment]
I looked through the JavaScript and the email and password are included in many of the headers, but they're not encoded correctly.

Please have a look at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization, as well as the example I provided above.

**Comment by SongWithoutWords** [comment]
The implementation needs to look something like this:
``` javascript
function postData(url = ``, data = {}, email="", password ="") {
  // Default options are marked with *
  return fetch(url, {
    method: "POST",
    headers: {
      Accept: "application/json",
      Authorization: "Basic " + encodeBase64(email + " " + password)
    },
    body: JSON.stringify(data)
  }).then(checkRequestErrors);
}
```
I don't have the tools for the frontend, so I can't verify that this code compiles, but it needs to look something like this (for many of our requests)

**Comment by ZhihangZhang** [comment]
okay, I'll change the code and push it

**Comment by SongWithoutWords** [comment]
Thanks man :smile:

**Comment by ZhihangZhang** [comment]
no problem

**Comment by SongWithoutWords** [comment]
Acutally, if you copied my code it's wrong: it needs ":" between email and password rather than " "

**Comment by SongWithoutWords** [comment]
This appears to be done
