### ISSUE TITLE
[front-end] prescription list "Cannot read property 'amountInitial' of undefined" 

### ISSUE THREAD

**Issue by vagueanxiety** [SongWithoutWords/mapp#53]
After patient creates a new prescription:
`TypeError: TypeError: TypeError: Cannot read property 'amountInitial' of undefined
This error is located at:
    in PrescriptionListScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:45)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:45)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:45)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:45)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
...
`
Update: This error goes away after commenting out code related to notification

**Comment by SongWithoutWords** [comment]
I don't think you guys should have 3 assignees per task (it makes it unclear who's doing and responsible for what)
